dist: trusty
sudo: true
language: cpp
compiler:
    - gcc
    - clang

before_install:

env:
    - CXX_STANDARD=11
    - CXX_STANDARD=14
    - CXX_STANDARD=17

script: ./build_and_test.sh

notifications:
  email: false
