dist: xenial
sudo: required
language: cpp

before_install:

matrix:
    include:

    - os linux
        compiler: gcc
        env:
            - COMPILER=g++-5
            - CXX_STANDARD=11
            - CXX_STANDARD=14
            - CXX_STANDARD=17
        addons:
        apt:
            sources: ['ubuntu-toolchain-r-test']
            packages: ['g++-5', 'ninja-build']

script: ./build_and_test.sh

notifications:
  email: false
